-r,--reverseオプションを追加
ItohYuto/ruby-practices pull request #7
Opened 2023-11-22 00:41 UTC by ItohYuto

- ```-r```,```--reverse```オプションがある場合、降順にする。

2023-11-27 09:50 UTC, u1tnk requested changes

2023-11-27 09:50 UTC, u1tnk commented on 04.ls/ls.rb
> +    files.sort_by { |filename| filename.delete_prefix('.').downcase }.reverse
ブロックの時点で逆になるようにしているなら処理の無駄を省く意味もありますが、これだとreverse以外はただの重複なので、重複排除した 方が良いと思います。

2023-11-28 02:32 UTC, ItohYuto commented on 04.ls/ls.rb
> +    files.sort_by { |filename| filename.delete_prefix('.').downcase }.reverse
修正しました！

2023-11-28 02:33 UTC, ItohYuto commented
## 実行結果
- オプションなし
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/01b86fc8-8e03-42ca-a400-5a6b4fe2687c)
- -rオプション
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/e6f4c03d-dbfa-4f6c-bdd9-d44353b77458)

## OS標準のlsコマンド実行結果
- オプションなし
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/1f04a978-a944-4884-bf5f-5f1d424b64bd)
- -rオプション
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/bbdb5445-8b70-4bae-b779-6f86cacce67c)

## rubocop-fjordの実行結果
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/40f0b31f-46b6-402a-9a45-c8011e3bc026)

2023-11-28 15:05 UTC, u1tnk approved these changes

2023-11-28 23:52 UTC, merged