-lオプションの追加
ItohYuto/ruby-practices pull request #9
Opened 2023-11-30 01:48 UTC by ItohYuto

```-l```オプションがある場合、ロングフォーマットで出力する。

2023-11-30 16:34 UTC, u1tnk requested changes

2023-11-30 16:34 UTC, u1tnk commented on 04.ls/ls.rb
> +def output_long_format_files(long_format_files, total)
`long_format_files` とありますがメソッド名的に当然なので `files` で 良いと思います。

2023-11-30 16:34 UTC, u1tnk commented on 04.ls/ls.rb
> +def get_files_properties(sorted_files)
ここは sortされてるかどうかが重要では無さそうなので同じく `files` で良いと思いま。

2023-11-30 16:34 UTC, u1tnk commented on 04.ls/ls.rb
> +    file_details << format_filemode(file_stat.mode.to_s(8))
この配列で渡す方法はあまり良くないですね。

このプラクティスのみであればこれの方が簡潔ですが、業務の練習としては以下のような問題があります。

- output_long_format_files メソッドがこのメソッドの出力順に依存してしまっている。
    - 出力しているところとソートしているところが別なので理解しづらい。
- 配列は順番しか情報が無いので変更に弱いです。出力する内容が途中で一個増えたりするとかなり混乱することになります。

hashなどでデータの中身に名前を付けて渡すようにしましょう。

2023-11-30 16:34 UTC, u1tnk commented on 04.ls/ls.rb
> +  file_permission = filemode.slice(-3..-1).split(//).map { |n| PERMISSION_TYPE_MAP[n] }
細かいところですが、 `split(//)`は `chars` で良さそうですがどうでしょう？

2023-11-30 16:34 UTC, u1tnk commented on 04.ls/ls.rb
> +def align_string_length(strings, format = 'left')
このメソッド二回しか呼ばれてないのと、メソッドはなるべくシンプルに分けて再利用した方が良い観点から、切り分けなくても良さそうな気がします。作るとしても max_lengthの計算だけで良さそうです。

2023-12-01 02:03 UTC, ItohYuto commented
ファイルのプロパティをハッシュで管理するように変更しました。
再度レビューお願いいたします。

## 実行結果
- ls オプションなし
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/da253810-929f-43cc-af8a-bba3552a7fe5)

- ls -l
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/5da70e6f-9707-4016-9e4f-90d022782152)

- totalの確認
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/ba706af1-ddba-433a-a778-01fc31b0f8b0)

## OS標準コマンドの実行結果
- ls オプションなし
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/14991d15-d06a-4773-bf52-8d5a3dfd512a)

- ls -l
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/1a481115-7759-4632-aa22-2d3d921a50e9)

- totalの確認
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/53a59e1c-7137-4411-beaf-c3c9ba7860d4)

## rubocop-fjordの実行結果
![image](https://github.com/ItohYuto/ruby-practices/assets/88817643/fe0bf996-f03c-45c9-bda6-6e7e59f86b9e)

2023-12-01 02:03 UTC, ItohYuto commented on 04.ls/ls.rb
> +  file_permission = filemode.slice(-3..-1).split(//).map { |n| PERMISSION_TYPE_MAP[n] }
修正しました。

2023-12-01 02:03 UTC, ItohYuto commented on 04.ls/ls.rb
> +    file_details << format_filemode(file_stat.mode.to_s(8))
ファイルのプロパティをハッシュで管理するように変更しました。

2023-12-01 02:04 UTC, ItohYuto commented on 04.ls/ls.rb
> +def get_files_properties(sorted_files)
修正しました。

2023-12-01 02:04 UTC, ItohYuto commented on 04.ls/ls.rb
> +def output_long_format_files(long_format_files, total)
修正しました。

2023-12-01 02:05 UTC, ItohYuto commented on 04.ls/ls.rb
> +def align_string_length(strings, format = 'left')
プロパティ別に最大長を算出し、ハッシュで返す関数に変更しました。
実際の文字列の長さは出力時に作成するようにしました。

2023-12-01 16:22 UTC, u1tnk approved these changes

2023-12-04 01:32 UTC, merged